### ISSUE TITLE
Improve performance of IDB.Translate.BCP

### ISSUE THREAD

**Issue by MarkusCool** [coolOrangeLabs/powerload-utilities#61] opened 2022-02-09 16:37 UTC
Description
========

The IDB.Translate.BCP takes to long. Especially the writing of the File-File-Realation is taking too much time.
E.g. for creating a BCP-packge with about 1.7 million file-file relations it took 3 days for reseller Graitec. The machine has 32 GB RAM and a 2.9 GH processor. CPU load is at 27%, Memory at 70%.

Support
======
* [IMI](https://app-eu1.hubspot.com/contacts/25067259/ticket/818184893)
  * [IMI logs and time sheets.zip](https://github.com/coolOrangeLabs/powerload-utilities/files/9251985/IMI.logs.and.time.sheets.zip)

**Comment by kieninj** [comment] 2022-08-22 15:06
Duplicate of #66

**Closed by kieninj** 2022-08-22 15:06 UTC
Labels: duplicate, IDB.Translate.BCP
